#!/usr/bin/env bash
# A Script to display listening ports and filter

echo "Active Internet connections (only servers)"
ss -tuln -p | grep 'LISTEN'
echo "Active UNIX domain sockets (only servers)"
ss -xl -p | grep 'LISTEN'