#!/usr/bin/env bash
#A Bash script that displays Best School 10 times

NUMBER=0
while [ $NUMBER -lt 10 ]
do
    if [ $NUMBER == 9 ]
    then
        echo "Hi"
    fi
     echo "Best School"
    ((NUMBER ++))
done