#!/usr/bin/env bash
#A Bash script that displays Best School 10 times

NUMBER=0
while [ $NUMBER -lt 9 ]
do
    echo "Best School"

if [ $NUMBER -eq 7 ]; then
    echo "Hi"
fi    
    ((NUMBER ++))
done